# Running on r7n03
# Started at Wed Jun 9 12:05:37 EDT 2021
# /home/hltcoe/aarora/miniconda3/envs/k2/bin/python3 mmi_bigram_train.py 
World size: 1 Rank: 0
Added key: store_based_barrier_key:1 to store for rank: 0
Loading L.fst
About to get train cuts
Using BucketingSampler.
About to create train dataloader
About to create dev dataset
About to get dev cuts
About to create dev dataloader
About to create model
================================================================================
Model parameters summary:
================================================================================
* P_scores:                                                             10962720
* tdnn.0.weight:                                                          120000
* tdnn.0.bias:                                                               500
* tdnn.3.weight:                                                          750000
* tdnn.3.bias:                                                               500
* tdnn.6.weight:                                                          750000
* tdnn.6.bias:                                                               500
* lstms.0.weight_ih_l0:                                                  1000000
* lstms.0.weight_hh_l0:                                                  1000000
* lstms.0.bias_ih_l0:                                                       2000
* lstms.0.bias_hh_l0:                                                       2000
* lstms.1.weight_ih_l0:                                                  1000000
* lstms.1.weight_hh_l0:                                                  1000000
* lstms.1.bias_ih_l0:                                                       2000
* lstms.1.bias_hh_l0:                                                       2000
* lstms.2.weight_ih_l0:                                                  1000000
* lstms.2.weight_hh_l0:                                                  1000000
* lstms.2.bias_ih_l0:                                                       2000
* lstms.2.bias_hh_l0:                                                       2000
* lstms.3.weight_ih_l0:                                                  1000000
* lstms.3.weight_hh_l0:                                                  1000000
* lstms.3.bias_ih_l0:                                                       2000
* lstms.3.bias_hh_l0:                                                       2000
* lstms.4.weight_ih_l0:                                                  1000000
* lstms.4.weight_hh_l0:                                                  1000000
* lstms.4.bias_ih_l0:                                                       2000
* lstms.4.bias_hh_l0:                                                       2000
* linear.weight:                                                         1655500
* linear.bias:                                                              3311
================================================================================
Total: 24263031
================================================================================
epoch 0, learning rate 0.001
Traceback (most recent call last):
  File "mmi_bigram_train.py", line 513, in <module>
    main()
  File "mmi_bigram_train.py", line 441, in main
    objf, valid_objf, global_batch_idx_train = train_one_epoch(
  File "mmi_bigram_train.py", line 191, in train_one_epoch
    curr_batch_objf, curr_batch_frames, curr_batch_all_frames = get_objf(
  File "mmi_bigram_train.py", line 106, in get_objf
    mmi_loss, tot_frames, all_frames = loss_fn(nnet_output, texts, supervision_segments)
  File "/home/hltcoe/aarora/miniconda3/envs/k2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/hltcoe/aarora/snowfall/snowfall/objectives/mmi.py", line 222, in forward
    return func(nnet_output=nnet_output,
  File "/home/hltcoe/aarora/snowfall/snowfall/objectives/mmi.py", line 84, in _compute_mmi_loss_exact_optimized
    num_den_reordered_graphs = k2.index(num_den_graphs, num_den_graphs_indexes)
  File "/home/hltcoe/aarora/miniconda3/envs/k2/lib/python3.8/site-packages/k2/ops.py", line 317, in index
    return index_fsa(src, indexes)
  File "/home/hltcoe/aarora/miniconda3/envs/k2/lib/python3.8/site-packages/k2/ops.py", line 222, in index_fsa
    ragged_arc, value_indexes = k2.ragged.index(src.arcs,
  File "/home/hltcoe/aarora/miniconda3/envs/k2/lib/python3.8/site-packages/k2/ragged/ops.py", line 52, in index
    ans, value_indexes = _k2.index(src=src,
RuntimeError: CUDA out of memory. Tried to allocate 17179869180.67 GiB (GPU 0; 31.75 GiB total capacity; 3.54 GiB already allocated; 26.87 GiB free; 3.69 GiB reserved in total by PyTorch)
Exception raised from malloc at /opt/conda/conda-bld/pytorch_1616554788289/work/c10/cuda/CUDACachingAllocator.cpp:288 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x2aab196752f2 in /home/hltcoe/aarora/miniconda3/envs/k2/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x1bc21 (0x2aab19411c21 in /home/hltcoe/aarora/miniconda3/envs/k2/lib/python3.8/site-packages/torch/lib/libc10_cuda.so)
frame #2: <unknown function> + 0x1c944 (0x2aab19412944 in /home/hltcoe/aarora/miniconda3/envs/k2/lib/python3.8/site-packages/torch/lib/libc10_cuda.so)
frame #3: <unknown function> + 0x1cf63 (0x2aab19412f63 in /home/hltcoe/aarora/miniconda3/envs/k2/lib/python3.8/site-packages/torch/lib/libc10_cuda.so)
frame #4: k2::PytorchCudaContext::Allocate(unsigned long, void**) + 0x33 (0x2aab34cb3583 in /home/hltcoe/aarora/miniconda3/envs/k2/lib/python3.8/site-packages/libk2context.so)
frame #5: k2::NewRegion(std::shared_ptr<k2::Context>, unsigned long) + 0x11e (0x2aab349ffffe in /home/hltcoe/aarora/miniconda3/envs/k2/lib/python3.8/site-packages/libk2context.so)
frame #6: <unknown function> + 0x24be21 (0x2aab34b7fe21 in /home/hltcoe/aarora/miniconda3/envs/k2/lib/python3.8/site-packages/libk2context.so)
frame #7: <unknown function> + 0x269eb4 (0x2aab34b9deb4 in /home/hltcoe/aarora/miniconda3/envs/k2/lib/python3.8/site-packages/libk2context.so)
frame #8: k2::Index(k2::RaggedShape&, int, k2::Array1<int> const&, k2::Array1<int>*) + 0x1da (0x2aab34ba045a in /home/hltcoe/aarora/miniconda3/envs/k2/lib/python3.8/site-packages/libk2context.so)
frame #9: <unknown function> + 0xa0bf1 (0x2aab33da7bf1 in /home/hltcoe/aarora/miniconda3/envs/k2/lib/python3.8/site-packages/_k2.cpython-38-x86_64-linux-gnu.so)
frame #10: <unknown function> + 0x923e7 (0x2aab33d993e7 in /home/hltcoe/aarora/miniconda3/envs/k2/lib/python3.8/site-packages/_k2.cpython-38-x86_64-linux-gnu.so)
frame #11: <unknown function> + 0x1b8ff (0x2aab33d228ff in /home/hltcoe/aarora/miniconda3/envs/k2/lib/python3.8/site-packages/_k2.cpython-38-x86_64-linux-gnu.so)
frame #12: PyCFunction_Call + 0x58 (0x5555556a8348 in /home/hltcoe/aarora/miniconda3/envs/k2/bin/python3)
frame #13: _PyObject_MakeTpCall + 0x23c (0x555555697dbc in /home/hltcoe/aarora/miniconda3/envs/k2/bin/python3)
frame #14: _PyEval_EvalFrameDefault + 0x11db (0x5555557202ab in /home/hltcoe/aarora/miniconda3/envs/k2/bin/python3)
frame #15: _PyEval_EvalCodeWithName + 0x300 (0x5555556ed270 in /home/hltcoe/aarora/miniconda3/envs/k2/bin/python3)
frame #16: _PyFunction_Vectorcall + 0x1e3 (0x5555556ee0a3 in /home/hltcoe/aarora/miniconda3/envs/k2/bin/python3)
frame #17: <unknown function> + 0x10343c (0x55555565743c in /home/hltcoe/aarora/miniconda3/envs/k2/bin/python3)
frame #18: _PyFunction_Vectorcall + 0x10b (0x5555556edfcb in /home/hltcoe/aarora/miniconda3/envs/k2/bin/python3)
frame #19: <unknown function> + 0x1035db (0x5555556575db in /home/hltcoe/aarora/miniconda3/envs/k2/bin/python3)
frame #20: _PyFunction_Vectorcall + 0x10b (0x5555556edfcb in /home/hltcoe/aarora/miniconda3/envs/k2/bin/python3)
frame #21: <unknown function> + 0x103a61 (0x555555657a61 in /home/hltcoe/aarora/miniconda3/envs/k2/bin/python3)
frame #22: _PyEval_EvalCodeWithName + 0x300 (0x5555556ed270 in /home/hltcoe/aarora/miniconda3/envs/k2/bin/python3)
frame #23: _PyFunction_Vectorcall + 0x1e3 (0x5555556ee0a3 in /home/hltcoe/aarora/miniconda3/envs/k2/bin/python3)
frame #24: <unknown function> + 0x10343c (0x55555565743c in /home/hltcoe/aarora/miniconda3/envs/k2/bin/python3)
frame #25: _PyFunction_Vectorcall + 0x10b (0x5555556edfcb in /home/hltcoe/aarora/miniconda3/envs/k2/bin/python3)
frame #26: <unknown function> + 0x19a5d9 (0x5555556ee5d9 in /home/hltcoe/aarora/miniconda3/envs/k2/bin/python3)
frame #27: PyObject_Call + 0x414 (0x555555698754 in /home/hltcoe/aarora/miniconda3/envs/k2/bin/python3)
frame #28: _PyEval_EvalFrameDefault + 0x1fe6 (0x5555557210b6 in /home/hltcoe/aarora/miniconda3/envs/k2/bin/python3)
frame #29: _PyEval_EvalCodeWithName + 0x300 (0x5555556ed270 in /home/hltcoe/aarora/miniconda3/envs/k2/bin/python3)
frame #30: _PyObject_Call_Prepend + 0x181 (0x5555556eeb61 in /home/hltcoe/aarora/miniconda3/envs/k2/bin/python3)
frame #31: <unknown function> + 0x19af0a (0x5555556eef0a in /home/hltcoe/aarora/miniconda3/envs/k2/bin/python3)
frame #32: _PyObject_MakeTpCall + 0x23c (0x555555697dbc in /home/hltcoe/aarora/miniconda3/envs/k2/bin/python3)
frame #33: _PyEval_EvalFrameDefault + 0x475 (0x55555571f545 in /home/hltcoe/aarora/miniconda3/envs/k2/bin/python3)
frame #34: _PyEval_EvalCodeWithName + 0x8b1 (0x5555556ed821 in /home/hltcoe/aarora/miniconda3/envs/k2/bin/python3)
frame #35: _PyFunction_Vectorcall + 0x1e3 (0x5555556ee0a3 in /home/hltcoe/aarora/miniconda3/envs/k2/bin/python3)
frame #36: <unknown function> + 0x10343c (0x55555565743c in /home/hltcoe/aarora/miniconda3/envs/k2/bin/python3)
frame #37: _PyEval_EvalCodeWithName + 0x300 (0x5555556ed270 in /home/hltcoe/aarora/miniconda3/envs/k2/bin/python3)
frame #38: _PyFunction_Vectorcall + 0x1e3 (0x5555556ee0a3 in /home/hltcoe/aarora/miniconda3/envs/k2/bin/python3)
frame #39: <unknown function> + 0x10343c (0x55555565743c in /home/hltcoe/aarora/miniconda3/envs/k2/bin/python3)
frame #40: _PyFunction_Vectorcall + 0x10b (0x5555556edfcb in /home/hltcoe/aarora/miniconda3/envs/k2/bin/python3)
frame #41: <unknown function> + 0x1035db (0x5555556575db in /home/hltcoe/aarora/miniconda3/envs/k2/bin/python3)
frame #42: _PyEval_EvalCodeWithName + 0x300 (0x5555556ed270 in /home/hltcoe/aarora/miniconda3/envs/k2/bin/python3)
frame #43: PyEval_EvalCode + 0x23 (0x555555782543 in /home/hltcoe/aarora/miniconda3/envs/k2/bin/python3)
frame #44: <unknown function> + 0x22e5e4 (0x5555557825e4 in /home/hltcoe/aarora/miniconda3/envs/k2/bin/python3)
frame #45: <unknown function> + 0x254854 (0x5555557a8854 in /home/hltcoe/aarora/miniconda3/envs/k2/bin/python3)
frame #46: <unknown function> + 0x115390 (0x555555669390 in /home/hltcoe/aarora/miniconda3/envs/k2/bin/python3)
frame #47: PyRun_SimpleFileExFlags + 0x384 (0x55555566c0d2 in /home/hltcoe/aarora/miniconda3/envs/k2/bin/python3)
frame #48: <unknown function> + 0x118bf0 (0x55555566cbf0 in /home/hltcoe/aarora/miniconda3/envs/k2/bin/python3)
frame #49: Py_BytesMain + 0x39 (0x5555557aba09 in /home/hltcoe/aarora/miniconda3/envs/k2/bin/python3)
frame #50: __libc_start_main + 0xf5 (0x2aaaaaf0d445 in /lib64/libc.so.6)
frame #51: <unknown function> + 0x1e6fe5 (0x55555573afe5 in /home/hltcoe/aarora/miniconda3/envs/k2/bin/python3)

# Accounting: time=50 threads=1
# Finished at Wed Jun 9 12:06:27 EDT 2021 with status 1
